[package]
name = "riiry"
version = "0.1.0"
authors = ["Aaron Ash <aaron.ash@gmail.com>"]
edition = "2018"

[dependencies]
sublime_fuzzy = "0.6.0"

[dependencies.gtk]
version = "0.6.0"
features = ["v3_22"]

